### ISSUE TITLE
Path to db-dir treated differently in relative to the passed command (e.g., for list and uninstall)

### ISSUE THREAD

**Issue by bitia-org** [levenkov/rawpkg#2]
For command 'list' path to db-dir related to the rootdir path. For 'uninstall' it related to the current directory (in case of --db-dir ./blablabla) or is an absolute path (in case of --db-dir /blablabla).

Variant of 'uninstall' is more suitable.

**Comment by bitia-org** [comment]
Sorry, i'm wrong. For 'uninstall' in case of --db-dir ./blablabla path treated as related to rootdir, but absolute path is allowed.

**Comment by KaterinaPashkova** [comment]
Done
